### ISSUE TITLE
Rotated Image

### ISSUE THREAD

**Issue by jmann-williams** [jmann-williams/leafy-decorations#1]
@charlie-quinn - I accidentally rotated an image, it was too late to change it back when I realized and markbot says "cheater"

**Comment by charlie-quinn** [comment]
Grade has been updated manually! 🤖✅

**Comment by charlie-quinn** [comment]
⚠️`Reminder: please close this issue once it has been resolved.`

**Comment by charlie-quinn** [comment]
⚠️`Reminder: please close this issue once it has been resolved.`

**Comment by charlie-quinn** [comment]
⚠️Reminder: please close this issue once it has been resolved.

**Comment by charlie-quinn** [comment]
⚠️`Reminder: please close this issue once it has been resolved.`
